import { createSlice } from '@reduxjs/toolkit';
import { mockNotes } from '../../data/mockData';

const notesSlice = createSlice({
  name: 'notes',
  initialState: {
    notes: mockNotes,
    currentNote: null,
    loading: false,
    error: null,
    searchResults: [],
    filters: {
      category: '',
      search: ''
    }
  },
  reducers: {
    // Note management
    createNote: (state, action) => {
      const newNote = {
        ...action.payload,
        _id: Date.now().toString(),
        user: '1',
        aiAnalysis: null,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      };
      state.notes.unshift(newNote);
    },
    
    updateNote: (state, action) => {
      const index = state.notes.findIndex(note => note._id === action.payload.id);
      if (index !== -1) {
        state.notes[index] = {
          ...state.notes[index],
          ...action.payload,
          updatedAt: new Date().toISOString()
        };
      }
    },
    
    deleteNote: (state, action) => {
      state.notes = state.notes.filter(note => note._id !== action.payload);
    },
    
    setCurrentNote: (state, action) => {
      state.currentNote = action.payload;
    },
    
    // Search and filters
    searchNotes: (state, action) => {
      const { query, category } = action.payload;
      state.filters.search = query;
      state.filters.category = category;
      
      let filteredNotes = state.notes;
      
      if (query) {
        const searchTerm = query.toLowerCase();
        filteredNotes = filteredNotes.filter(note => 
          note.title.toLowerCase().includes(searchTerm) ||
          note.content.toLowerCase().includes(searchTerm) ||
          note.tags?.some(tag => tag.toLowerCase().includes(searchTerm)) ||
          note.aiAnalysis?.keywords?.some(keyword => keyword.toLowerCase().includes(searchTerm))
        );
      }
      
      if (category) {
        filteredNotes = filteredNotes.filter(note => note.category === category);
      }
      
      state.searchResults = filteredNotes;
    },
    
    clearSearch: (state) => {
      state.searchResults = [];
      state.filters.search = '';
      state.filters.category = '';
    },
    
    // AI Analysis
    analyzeNote: (state, action) => {
      const noteId = action.payload;
      const note = state.notes.find(n => n._id === noteId);
      if (note) {
        // Mock AI analysis
        note.aiAnalysis = {
          summary: 'This is a mock AI-generated summary for demonstration purposes. In the real app, this would be generated by OpenAI API.',
          keywords: ['mock', 'demo', 'ai', 'analysis', 'sample'],
          questions: [
            'What is the main topic of this note?',
            'What are the key points discussed?',
            'How can this information be applied?',
            'What related concepts should be explored?',
            'What are the potential implications?'
          ],
          simplifiedContent: 'This is a simplified version of the content generated by mock AI. In the production version, this would be properly generated by AI algorithms.',
          tone: 'academic',
          lastAnalyzed: new Date().toISOString()
        };
      }
    },
    
    setLoading: (state, action) => {
      state.loading = action.payload;
    },
    
    setError: (state, action) => {
      state.error = action.payload;
    }
  }
});

export const {
  createNote,
  updateNote,
  deleteNote,
  setCurrentNote,
  searchNotes,
  clearSearch,
  analyzeNote,
  setLoading,
  setError
} = notesSlice.actions;

export default notesSlice.reducer;